---
jobs:
  - name: hello-world
    plan:
      - task: hello-world
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: perl, tag: slim-threaded-stretch}
          run:
            path: perl
            args:
              - -e
              - print 'hello world\n';
              - exit 1;
