---
jobs:
  - name: hello-world
    plan:
      - task: hello-world
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: {repository: busybox, tag: latest}
          run:
            path: sh
            args:
              - -ec
              - |
                echo Hello World
                echo Hi
                echo Wolrd
